[package]
name = "merpati"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["http1", "client"] }
hyper-util = { version = "0.1.14", features = ["http1", "client", "tokio"] }
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
