[toolchain]
channel = "nightly-2025-06-11"
profile = "minimal"
components = [
  "rustfmt",       # formatting
  "rust-analyzer", # IDE support
  "rust-src",      # stdlib source code
  "cargo",         # package manager
  "clippy",        # linter
]
targets = [
  "x86_64-unknown-linux-gnu"
]

