[package]
name = "merpati-script"
repository.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
starlark.workspace = true
tracing.workspace = true
