name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-06-11

      - name: Install Nushell
        uses: hustcer/setup-nu@v1
        with:
          version: latest

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install \
            build-essential \
            git \
            pkg-config \
            libdbus-1-dev \
            libudev-dev \
            libxkbcommon-dev \
            libfontconfig1-dev \
            libasound2-dev

      - name: Build
        id: build
        run: |
          nu ./x/release/build.nu build x86_64-unknown-linux-gnu
          echo "version=$(nu ./x/release/changelog.nu ver)" >> $GITHUB_OUTPUT
          echo "artifact-path=$(nu ./x/release/build.nu archive-path x86_64-unknown-linux-gnu)" >> $GITHUB_OUTPUT
          echo "artifact-name=$(nu ./x/release/build.nu archive-name x86_64-unknown-linux-gnu)" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: merpati-${{ steps.build.outputs.version }}--${{ steps.build.outputs.artifact-name }}
          path: ${{ steps.build.outputs.artifact-path }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Nushell
        uses: hustcer/setup-nu@v1
        with:
          version: 'latest'
          
      - name: Get Changelog Information
        id: changelog
        run: |
          echo "version=$(nu ./x/release/changelog.nu ver)" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT; nu ./x/release/changelog.nu get >> $GITHUB_OUTPUT; echo "EOF" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: merpati-${{ steps.changelog.outputs.version }}--*
          path: artifacts
          merge-multiple: true
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true
          files: artifacts/*
